name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install gcc
      run: sudo apt install gcc-riscv64-unknown-elf
    - name: Install binutils
      run: sudo apt install binutils-riscv64-unknown-elf
    - name: Set nightly
      run: rustup default nightly
    - name: Get rust-src
      run: rustup component add rust-src
    - name: Add target
      run: rustup target add riscv64gc-unknown-none-elf
    - name: Run doc
      run: TOOLPREFIX=riscv64-unknown-elf- cargo doc --no-deps
      working-directory: kernel
    - name: Deploy
      uses: actions/upload-pages-artifact@v1
      with:
        path: kernel/target/riscv64gc-unknown-none-elf/doc

  deploy:
     needs: doc
     permissions:
       pages: write
       id-token: write
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v1